// <auto-generated />
using Funcy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Funcy.Data.Migrations
{
    [DbContext(typeof(FunctionAppDbContext))]
    partial class FunctionAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Funcy.Data.Entities.Function", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FunctionAppId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FunctionAppId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionAppId");

                    b.HasIndex("FunctionAppId1");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FunctionApps");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionAppSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FunctionAppId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FunctionAppId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionAppId");

                    b.HasIndex("FunctionAppId1");

                    b.ToTable("FunctionAppSlots");
                });

            modelBuilder.Entity("Funcy.Data.Entities.Function", b =>
                {
                    b.HasOne("Funcy.Data.Entities.FunctionApp", null)
                        .WithMany("Functions")
                        .HasForeignKey("FunctionAppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Funcy.Data.Entities.FunctionApp", "FunctionApp")
                        .WithMany()
                        .HasForeignKey("FunctionAppId1");

                    b.Navigation("FunctionApp");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionAppSlot", b =>
                {
                    b.HasOne("Funcy.Data.Entities.FunctionApp", null)
                        .WithMany("Slots")
                        .HasForeignKey("FunctionAppId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Funcy.Data.Entities.FunctionApp", "FunctionApp")
                        .WithMany()
                        .HasForeignKey("FunctionAppId1");

                    b.Navigation("FunctionApp");
                });

            modelBuilder.Entity("Funcy.Data.Entities.FunctionApp", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
